name: gromore
description: 穿山甲gromore聚合广告插件flutter版
version: 0.0.2
homepage: https://github.com/gstory0404/gromore

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.gstory.gromore
        pluginClass: GromorePlugin
      ios:
        pluginClass: GromorePlugin
